apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-rolling-update
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        role: rolling-update
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.17
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
  strategy:
    type: RollingUpdate
    rollingUp:
      maxSurge: 50%
